baseURL: https://www.chriswlucas.com/
languageCode: en-us
title: Chris Lucas

theme: anubis

paginate: 10
enableRobotsTXT: true
enableGitInfo: true

markup:
  goldmark:
    extensions:
      linkify: true
  highlight:
    style: monokailight

menu:
  main:
  - name: About
    pageRef: about
    weight: 10
  - name: Projects
    pageRef: projects
    weight: 20
  # - name: Favorites
  #   pageRef: tags/favorite
  #   weight: 25
  - name: Archive
    pageRef: posts
    weight: 30

  footer:
  - name: Categories
    pageRef: categories
    weight: 1
  - name: Tags
    pageRef: tags
    weight: 2

params:
  author: Christopher Lucas

  description: Chris Lucas' Blog # TODO: about.md shows up in HTML??
  email: chris@chriswlucas.com
  # TODO: avatar?

  social:
  - id: email
    name: chris@chriswlucas.com
  - id: github
    name: cwlucas41
  - id: keybase
    url: https://keybase.io/cwlucas41
  - id: twitter
    name: cwlucas41
  - id: linkedin
    name: cwlucas41
  rssAsSocialIcon: true

  readMore: true

  dateFormat: 2006-01-02
  copyCodeButton: true
  style: light-without-switcher # TODO: fix code syntax

deployment:
  targets:
  - name: cloudFront
    URL: s3://www.chriswlucas.com/?region=us-east-1
    cloudFrontDistributionID: E2TJ2NWTOLW2J0